# Generated by Django 5.0.4 on 2024-04-17 00:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=30)),
                ('email_Address', models.EmailField(max_length=30, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='email_Address',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='password',
        ),
        migrations.AddField(
            model_name='lista',
            name='descripcion',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reseña',
            name='puntuacion',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.FileField(default='default.txt', upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videojuego',
            name='portada',
            field=models.FileField(default='default.txt', upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lista',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='EstaEn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.lista')),
                ('videojuego', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='domain.videojuego')),
            ],
        ),
        migrations.CreateModel(
            name='LeGusta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.lista')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Siguen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguido_por', to='domain.usuario')),
                ('seguidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sigue_a', to='domain.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Pertence',
        ),
    ]
