# Generated by Django 5.0.4 on 2024-04-17 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_cuenta_remove_usuario_email_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cuenta',
            field=models.OneToOneField( on_delete=django.db.models.deletion.CASCADE, to='domain.cuenta'),
        ),
    ]
