# Generated by Django 5.0.4 on 2024-04-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_usuario_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
