# Generated by Django 5.0.4 on 2024-04-19 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_alter_usuario_foto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lista',
            new_name='ListaDeJuegos',
        ),
    ]
