# Generated by Django 5.0.4 on 2024-04-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0005_rename_lista_listadejuegos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='portada',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
