# Generated by Django 5.0.4 on 2024-04-26 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0008_alter_listadejuegos_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estaen',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenido', to='domain.listadejuegos'),
        ),
        migrations.AlterField(
            model_name='legusta',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='me_gustan', to='domain.listadejuegos'),
        ),
    ]
