# Generated by Django 5.0.4 on 2024-05-17 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0011_alter_reseña_game_alter_reseña_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estaen',
            name='videojuego',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listas', to='domain.videojuego'),
        ),
    ]
