# Generated by Django 5.0.4 on 2024-05-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0012_alter_estaen_videojuego'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='descripcion',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
