# Generated by Django 5.0.4 on 2024-05-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0014_cuenta_groups_cuenta_is_active_cuenta_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseña',
            name='content',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
