# Generated by Django 5.0.4 on 2024-05-19 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0015_alter_reseña_content'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estaen',
            unique_together={('videojuego', 'lista')},
        ),
    ]
