# Generated by Django 5.0.4 on 2024-06-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0021_alter_usuario_cuenta_delete_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='descripcion',
            field=models.CharField(default='', max_length=1500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='portada',
            field=models.FileField(default='', upload_to='media/uploads/'),
            preserve_default=False,
        ),
    ]
