# Generated by Django 5.0.4 on 2024-06-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0022_alter_videojuego_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
